canonical: https://www.ehealth.fgov.be/standards/fhir/eattestation
fhirVersion: 4.0.1
FSHOnly: false
applyExtensionMetadataToRoot: false
id: hl7.fhir.be.eattestation
name: Belgian MyCareNet eAttestation Profiles
title: Belgian MyCareNet eAttestation Profiles
status: draft
version: 1.0.0
copyrightYear: 2023+
releaseLabel: STU
jurisdiction: urn:iso:std:iso:3166#BE "Belgium"
# The publisher can be a single item or a list, each with a name and
# optional url and/or email. The first publisher's name will be used
# as IG.publisher.  The contact details and/or additional publishers
# will be translated into IG.contact values.
publisher:
  name: eHealth Platform
  url: http://www.ehealth.fgov.be/
  email: support@be-ehealth-standards.atlassian.net
dependencies:
  hl7.fhir.be.core: current
  hl7.fhir.be.core-clinical: current
  hl7.fhir.be.nihdi-terminology: current
  hl7.fhir.be.mycarenet: current$issue-46
  

# The pages property corresponds to IG.definition.page. SUSHI can
# auto-generate the page list, but if the author includes pages in
# this file, it is assumed that the author will fully manage the
# pages section and SUSHI will not generate any page entries.
# The page file name is used as the key. If title is not provided,
# then the title will be generated from the file name.  If a
# generation value is not provided, it will be inferred from the
# file name extension.  Any subproperties that are valid filenames
# with supported extensions (e.g., .md/.xml) will be treated as
# sub-pages.
pages:
  index.xml:
    title: Home
  guidance.md:
  changes.xml:
  downloads.xml:
  
# The ImplementationGuide resource defines several other properties
# not represented above. These properties can be used as-is and
# should follow the format defined in ImplementationGuide:
# * meta
# * implicitRules
# * language
# * text
# * contained
# * extension
# * modifierExtension
# * experimental
# * useContext
# * copyright
# * packageId

# The menu property will be used to generate the input/menu.xml file.
# The menu is represented as a simple structure where the YAML key
# is the menu item name and the value is the URL. The IG publisher
# currently only supports one level deep on sub-menus.
# To provide a custom menu.xml file, do not include this property and
# include a `menu.xml` file in input/includes.
menu:
  Home: index.html
  Guidance: guidance.html
  Artifacts:
    Profiles: artifacts.html#2
    Extensions: artifacts.html#3
    Value Sets: artifacts.html#4
  Downloads: downloads.html
  Changes: changes.html
  History: "https://www.ehealth.fgov.be/standards/fhir/eattestation/history.html"


parameters:
  shownav: 'true'
  apply-contact: 'true'
  apply-jurisdiction: 'true'
  apply-publisher: 'true'
  apply-version: 'true' 

resources:
  Bundle/ex01:
     name: ex01
     description: All eAttestCreateRequest
  Bundle/ex02:
     name: ex02
     description: All eAttestCreateResponse
  Bundle/ex03:
     name: ex03
     description: All eAttestCancelRequest
  Bundle/ex04:
     name: ex04
     description: All eAttestCancelResponse
  Bundle/ex05:
     name: ex05
     description: Dentistry eAttestCreateRequest
  Bundle/ex06:
     name: ex06
     description: Dentistry eAttestCreateResponse
  Bundle/ex07:
     name: ex07
     description: Specializedmedicine within Hospital eAttestCreateRequest
  Bundle/ex08:
     name: ex08
     description: Specializedmedicine within Hospital eAttestCreateResponse
  Bundle/ex09:
     name: ex09
     description: Physiotherapy eAttestCreateRequest
  Bundle/ex10:
     name: ex10
     description: Physiotherapy eAttestCreateResponse
  Bundle/ex11:
     name: ex11
     description: GeneralPractice eAttestCreateRequest
  Bundle/ex12:
     name: ex12
     description: GeneralPractice eAttestCreateResponse
  Bundle/ex13:
     name: ex13
     description: GeneralPractice eAttestCancelRequest
  Bundle/ex14:
     name: ex14
     description: GeneralPractice eAttestCancelResponse
  Bundle/ex15:
     name: ex15
     description: Specializedmedicine within Hospital eAttestCancelRequest
  Bundle/ex16:
     name: ex16
     description: Specializedmedicine within Hospital eAttestCancelResponse
  Bundle/ex17:
     name: ex17
     description: All eAttestReject
           


