canonical: https://www.ehealth.fgov.be/standards/fhir/mycarenet
fhirVersion: 4.0.1
FSHOnly: false
applyExtensionMetadataToRoot: false
id: hl7.fhir.be.mycarenet
name: Belgian MyCareNet Profiles (V1.0)
title: Belgian MyCareNet Profiles (V1.0)
status: active
version: "1.0"
copyrightYear: 2022+
releaseLabel: STU
dependencies:
  hl7.fhir.be.core: 2.0.0
